import "./globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"

import { Toaster } from "@/components/ui/toaster";

const inter = Quicksand({
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={inter.className}>
                    <div>
                        <Toaster />
                        {children}
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
